export const exercises = [
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/uWuJH4FzcCoakH",
    id: "0001",
    name: "3/4 sit-up",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/0FzcgxUIhTGNO1",
    id: "0002",
    name: "45° side bend",
    target: "abs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/Z8QJWoPmCiLmNR",
    id: "0003",
    name: "air bike",
    target: "abs",
  },
  {
    bodyPart: "upper legs",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/zzDsVh4EYhx-6a",
    id: "1512",
    name: "all fours squad stretch",
    target: "quads",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/-MTBYlV9EIN-mZ",
    id: "0006",
    name: "alternate heel touchers",
    target: "abs",
  },
  {
    bodyPart: "back",
    equipment: "cable",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/6Ncy74qPjJrg63",
    id: "0007",
    name: "alternate lateral pulldown",
    target: "lats",
  },
  {
    bodyPart: "lower legs",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/xqIdrFjBjeoLaR",
    id: "1368",
    name: "ankle circles",
    target: "calves",
  },
  {
    bodyPart: "back",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/y0MlzBiPk6trqq",
    id: "3293",
    name: "archer pull up",
    target: "lats",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/FsU4YFlaDqu489",
    id: "3294",
    name: "archer push up",
    target: "pectorals",
  },
  {
    bodyPart: "lower arms",
    equipment: "weighted",
    gifUrl: "https://edb-4rme8.ondigitalocean.app/image/vlnJw6X85FZp8Z",
    id: "0859",
    name: "wrist rollerer",
    target: "forearms",
  },
];
